### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/stream-producer#38]
**Describe the bug**
When running a test of 25M (i.e. 25M - 50M of 100M)  The stream-loader died with the following error:

```console
Exception in thread Process-0-FilterUrlGzippedJsonToDictQueueThread-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/app/stream-producer.py", line 1567, in run
    for message in self.read():
  File "/app/stream-producer.py", line 1051, in read
    for line in data:
  File "/usr/lib/python3.7/gzip.py", line 374, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 469, in read
    buf = self._fp.read(io.DEFAULT_BUFFER_SIZE)
  File "/usr/lib/python3.7/gzip.py", line 91, in read
    self.file.read(size-self._length+read)
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by docktermj** [comment]
A thought would be be to restart using the last known line number, `output_counter_line_number_in_file`.   This line number is reported in the statistics.

```JSON
{
	"input_counter_interval": 90341,
	"input_counter_line_number_in_file": 32451177,
	"input_counter_rate_interval": 1505,
	"input_counter_rate_total": 1475,
	"input_counter_total": 7451176,
	"output_counter_interval": 90331,
	"output_counter_line_number_in_file": 32450959,
	"output_counter_rate_interval": 1505,
	"output_counter_rate_total": 1474,
	"output_counter_total": 7450958,
	"uptime": 5051,
	"workers_active": 31,
	"workers_total": 31
}
```
